# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DEFAULT_HEADERS": "00_core.ipynb",
         "dt": "00_core.ipynb",
         "getDate": "00_core.ipynb",
         "from_fleming": "00_core.ipynb",
         "main": "00_core.ipynb",
         "CONVERTER": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/convert_timemap/"

git_url = "https://github.com/fastai/convert_timemap/tree/master/"

def custom_doc_links(name): return None
