# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"repo_dir": "00_core.ipynb",
         "targets": "00_core.ipynb",
         "countries": "00_core.ipynb",
         "output": "00_core.ipynb",
         "output_xlsx": "00_core.ipynb",
         "DEFAULT_HEADERS": "00_core.ipynb",
         "COLS": "00_core.ipynb",
         "dt": "00_core.ipynb",
         "getDate": "00_core.ipynb",
         "from_fleming": "00_core.ipynb",
         "write_sheet": "00_core.ipynb",
         "write_xlsx_from_json": "00_core.ipynb",
         "CONVERTER": "00_core.ipynb",
         "random_distinct_colors": "00_core.ipynb",
         "distinct_colors": "00_core.ipynb",
         "derive_latlon": "00_core.ipynb",
         "flatmap": "00_core.ipynb",
         "get_files": "00_core.ipynb",
         "rewrite_xlsx_data": "00_core.ipynb",
         "gen_templates": "00_core.ipynb",
         "by_size": "00_core.ipynb",
         "matching": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/convert_timemap/"

git_url = "https://github.com/fastai/convert_timemap/tree/master/"

def custom_doc_links(name): return None
