# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['DEFAULT_HEADERS', 'dt', 'getDate', 'from_fleming', 'write_sheet', 'write_xlsx_from_json', 'CONVERTER']

# Cell
import json
import xlsxwriter
from datetime import datetime
from fastscript import *

# Cell
DEFAULT_HEADERS = [
    "id",
    "description",
    "location",
    "date",
    "time",
    "latitude",
    "longitude",
    "category",
    "filter0",
    "colour"
]

# Cell
def dt(d: str) -> datetime:
    return datetime.strptime(d, '%Y-%m-%dT%H:%M:%SZ')

def getDate(item: str) -> datetime:
    lspt = item.get('lastSpotted')
    if lspt is not None:
        return dt(lspt)
    startTime = item.get('startTime')
    if startTime is not None:
        return dt(startTime)
    endTime = item.get('endTime')
    if endTime is not None:
        return dt(endTime)
    raise Exception("JSON value doesn't have lastSpotted, startTime, or endTime")

def from_fleming(jdata, color):
    headers = DEFAULT_HEADERS
    odata = []
    past_locations = {}
    for idx, d in enumerate(jdata):
        thedate = getDate(d)
        lat = d['coordinates']['lat']
        lon = d['coordinates']['lon']
        locname = f"location{idx}"
        k = f"{lat}_{lon}"
        if past_locations.get(k) is not None:
            locname = past_locations[k]
        else:
            past_locations[f"{lat}_{lon}"] = locname
        rdata = [
            idx,
            d['targetId'],
            locname,
            datetime.strftime(thedate, '%m/%d/%Y'),
            datetime.strftime(thedate, '%H:%M:%S'),
            lat,
            lon,
            "alpha", # just one category
            d['targetId'],
            color

        ]
        odata.append(rdata)

    return headers, odata

# Cell
CONVERTER = from_fleming

def write_sheet(sheet, hdrs, rows):
    row = 0
    col = 0

    for hdr in hdrs:
        sheet.write(row, col, hdr)
        col += 1

    row = 1
    col = 0

    for rdata in rows:
        col = 0
        for cell in rdata:
            sheet.write(row, col, cell)
            col += 1
        row += 1

@call_parse
def write_xlsx_from_json(inp:Param("Input file", str),
                 outp:Param("Output file", str)="out.xlsx",
                 color:Param("The color of events", str)="red",
                 tabname:Param('Name of tab', str)="export_events"):
    workbook = xlsxwriter.Workbook(outp)
    worksheet = workbook.add_worksheet(tabname)

    with open(inp, 'r') as f:
        data = json.load(f)

    conv_data = CONVERTER(data, color)
    headers = conv_data[0]
    row_data = conv_data[1]

    write_sheet(worksheet, headers, row_data)

    workbook.close()